services:
  web:
    build: .
    command: gunicorn sms.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  celery-worker:
    build: .
    command: celery -A sms worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - mysql
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A sms beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    depends_on:
      - redis
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports: []

volumes:
  mysql-data:
