# Generated by Django 5.2.4 on 2025-08-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_plan',
        ),
    ]
